{% set name = "echo" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 85338c5c6a52113875a9c03cddd77e8d2fc000f241e8d4769a627d0b321d973d
  patches:
    - patches/0001-fix-license-in-pyproject.toml.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<310]

requirements:
  build:
    - patch  # [not win]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - wheel
    - setuptools >=61.2
    - setuptools_scm
  run:
    - python
    - numpy
  run_constrained:
    - pyqt >=5.14

test:
  imports:
    - echo
    - echo.core
    - echo.selection
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest --pyargs echo.tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/glue-viz/echo
  summary: Callback Properties in Python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: Echo is a small library for attaching callback functions to property state changes.
  dev_url: https://github.com/glue-viz/echo
  doc_url: https://echo.readthedocs.io
  

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
