{% set name = "echo" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0487f835e38a51ae7487190a23e4a943d4e0179714f5a24df92a35782a53b331
  patches:
    - patches/0001-fix-license-in-pyproject.toml.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - setuptools >=61.2
    - setuptools-scm
  run:
    - python
    - numpy
  run_constrained:
    - pyqt >=5.14

test:
  imports:
    - echo
    - echo.core
    - echo.selection
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest --pyargs echo.tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/glue-viz/echo
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Callback Properties in Python
  description: Echo is a small library for attaching callback functions to property state changes.
  dev_url: https://github.com/glue-viz/echo
  doc_url: https://echo.readthedocs.io

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
