{% set name = "echo" %}
{% set version = "0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bd30f1aefb500061124f123e3bb40cc59287fb257c5d7829d6e4327f5884318b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - numpy
    - setuptools
    - qtpy
    - pyqt

test:
  imports:
    - echo
    - echo.qt

about:
  home: https://github.com/glue-viz/echo
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Callback Properties in Python

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
