{% set name = "echo" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5d5618331b6ac090d097df7aa468f0676cc88fbbbda64a650f42b4a1d80534b9
  patches:
    - patches/0001-fix-license-in-pyproject.toml.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - setuptools >=61.2
    - setuptools-scm
  run:
    - python
    - numpy
  run_constrained:
    - pyqt >=5.14

test:
  imports:
    - echo
    - echo.core
    - echo.selection
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest --pyargs echo.tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/glue-viz/echo
  summary: Callback Properties in Python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/glue-viz/echo
  doc_url: https://echo.readthedocs.io
  description: |
    Echo is a small library for attaching callback functions to property state changes.

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
